name: Frontend3 CI

on:
  push:
    paths:
      - 'frontend3/**'
  pull_request:
    paths:
      - 'frontend3/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend3

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install
      - run: npm run build
